import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

export type FinancingCalculatorUsed = {
    device_id:      string;
    total_amount:   number;
    weeks_selected: number;
}

export type UserCreditProfile = {
    country:          string;
    credit_tier:      CreditTier;
    customer_id:      string;
    is_new_to_credit: boolean;
}

export type CreditTier = "new" | "bronze" | "silver" | "gold";

export type DeviceContext = {
    brand:       string;
    device_id:   string;
    is_featured: boolean;
    model:       string;
    price_usd:   number;
}

export type PaymentCompleted = {
    amount:            number;
    loan_id:           string;
    remaining_balance: number;
}

export type LoanContext = {
    device_id:       string;
    loan_id:         string;
    total_amount:    number;
    weeks_remaining: number;
    weeks_total:     number;
}

export type CreditApplicationStepCompleted = {
    step_name:   string;
    step_number: number;
}

export type PaymentInitiated = {
    amount:  number;
    loan_id: string;
    method:  Method;
}

export type Method = "oxxo" | "bank_transfer";

/**
 * Structure for events that identify a user, with their user pieces
 */
export type CustomerIdentification = {
    /**
     * Customer's email address
     */
    email?: null | string;
    /**
     * The customer's phone
     */
    phone?: null | string;
}

export type DeviceViewed = {
    brand:              string;
    device_id:          string;
    price_usd:          number;
    weekly_installment: number;
}

export type CreditDecisionViewed = {
    credit_limit: number;
    decision:     Decision;
}

export type Decision = "approved" | "needs_review";

export type DeviceLockSimulated = {
    days_overdue: number;
    loan_id:      string;
}

export type CreditApplicationStarted = {
    device_id:     string;
    source_screen: string;
}

export type CreditApplicationSubmitted = {
    device_id:        string;
    income_bracket:   IncomeBracket;
    requested_amount: number;
}

export type IncomeBracket = "under_500" | "over_2000";

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: EventSpecification){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-3',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for FinancingCalculatorUsed.
 * 
 */
export function trackFinancingCalculatorUsed<T extends {} = any>(financingCalculatorUsed: FinancingCalculatorUsed & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = financingCalculatorUsed;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/financing_calculator_used/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow FinancingCalculatorUsed entity.
 */
export function createFinancingCalculatorUsed(financingCalculatorUsed: FinancingCalculatorUsed){
    return {
        schema: 'iglu:com.leospaybyplow/financing_calculator_used/jsonschema/1-0-0',
        data: financingCalculatorUsed
    }
}
/**
 * Track a Snowplow event for UserCreditProfile.
 * 
 */
export function trackUserCreditProfile<T extends {} = any>(userCreditProfile: UserCreditProfile & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = userCreditProfile;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/user_credit_profile/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow UserCreditProfile entity.
 */
export function createUserCreditProfile(userCreditProfile: UserCreditProfile){
    return {
        schema: 'iglu:com.leospaybyplow/user_credit_profile/jsonschema/1-0-0',
        data: userCreditProfile
    }
}
/**
 * Track a Snowplow event for DeviceContext.
 * 
 */
export function trackDeviceContext<T extends {} = any>(deviceContext: DeviceContext & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = deviceContext;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/device_context/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow DeviceContext entity.
 */
export function createDeviceContext(deviceContext: DeviceContext){
    return {
        schema: 'iglu:com.leospaybyplow/device_context/jsonschema/1-0-0',
        data: deviceContext
    }
}
/**
 * Track a Snowplow event for PaymentCompleted.
 * 
 */
export function trackPaymentCompleted<T extends {} = any>(paymentCompleted: PaymentCompleted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = paymentCompleted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/payment_completed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PaymentCompleted entity.
 */
export function createPaymentCompleted(paymentCompleted: PaymentCompleted){
    return {
        schema: 'iglu:com.leospaybyplow/payment_completed/jsonschema/1-0-0',
        data: paymentCompleted
    }
}
/**
 * Track a Snowplow event for LoanContext.
 * 
 */
export function trackLoanContext<T extends {} = any>(loanContext: LoanContext & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = loanContext;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/loan_context/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow LoanContext entity.
 */
export function createLoanContext(loanContext: LoanContext){
    return {
        schema: 'iglu:com.leospaybyplow/loan_context/jsonschema/1-0-0',
        data: loanContext
    }
}
/**
 * Track a Snowplow event for CreditApplicationStepCompleted.
 * 
 */
export function trackCreditApplicationStepCompleted<T extends {} = any>(creditApplicationStepCompleted: CreditApplicationStepCompleted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = creditApplicationStepCompleted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/credit_application_step_completed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CreditApplicationStepCompleted entity.
 */
export function createCreditApplicationStepCompleted(creditApplicationStepCompleted: CreditApplicationStepCompleted){
    return {
        schema: 'iglu:com.leospaybyplow/credit_application_step_completed/jsonschema/1-0-0',
        data: creditApplicationStepCompleted
    }
}
/**
 * Track a Snowplow event for PaymentInitiated.
 * 
 */
export function trackPaymentInitiated<T extends {} = any>(paymentInitiated: PaymentInitiated & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = paymentInitiated;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/payment_initiated/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow PaymentInitiated entity.
 */
export function createPaymentInitiated(paymentInitiated: PaymentInitiated){
    return {
        schema: 'iglu:com.leospaybyplow/payment_initiated/jsonschema/1-0-0',
        data: paymentInitiated
    }
}
/**
 * Track a Snowplow event for CustomerIdentification.
 * Structure for events that identify a user, with their user pieces
 */
export function trackCustomerIdentification<T extends {} = any>(customerIdentification: CustomerIdentification & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = customerIdentification;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosenterprises/customer_identification/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CustomerIdentification entity.
 */
export function createCustomerIdentification(customerIdentification: CustomerIdentification){
    return {
        schema: 'iglu:com.leosenterprises/customer_identification/jsonschema/1-0-0',
        data: customerIdentification
    }
}
/**
 * Track a Snowplow event for DeviceViewed.
 * 
 */
export function trackDeviceViewed<T extends {} = any>(deviceViewed: DeviceViewed & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = deviceViewed;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/device_viewed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow DeviceViewed entity.
 */
export function createDeviceViewed(deviceViewed: DeviceViewed){
    return {
        schema: 'iglu:com.leospaybyplow/device_viewed/jsonschema/1-0-0',
        data: deviceViewed
    }
}
/**
 * Track a Snowplow event for CreditDecisionViewed.
 * 
 */
export function trackCreditDecisionViewed<T extends {} = any>(creditDecisionViewed: CreditDecisionViewed & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = creditDecisionViewed;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/credit_decision_viewed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CreditDecisionViewed entity.
 */
export function createCreditDecisionViewed(creditDecisionViewed: CreditDecisionViewed){
    return {
        schema: 'iglu:com.leospaybyplow/credit_decision_viewed/jsonschema/1-0-0',
        data: creditDecisionViewed
    }
}
/**
 * Track a Snowplow event for DeviceLockSimulated.
 * 
 */
export function trackDeviceLockSimulated<T extends {} = any>(deviceLockSimulated: DeviceLockSimulated & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = deviceLockSimulated;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/device_lock_simulated/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow DeviceLockSimulated entity.
 */
export function createDeviceLockSimulated(deviceLockSimulated: DeviceLockSimulated){
    return {
        schema: 'iglu:com.leospaybyplow/device_lock_simulated/jsonschema/1-0-0',
        data: deviceLockSimulated
    }
}
/**
 * Track a Snowplow event for CreditApplicationStarted.
 * 
 */
export function trackCreditApplicationStarted<T extends {} = any>(creditApplicationStarted: CreditApplicationStarted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = creditApplicationStarted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/credit_application_started/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CreditApplicationStarted entity.
 */
export function createCreditApplicationStarted(creditApplicationStarted: CreditApplicationStarted){
    return {
        schema: 'iglu:com.leospaybyplow/credit_application_started/jsonschema/1-0-0',
        data: creditApplicationStarted
    }
}
/**
 * Track a Snowplow event for CreditApplicationSubmitted.
 * 
 */
export function trackCreditApplicationSubmitted<T extends {} = any>(creditApplicationSubmitted: CreditApplicationSubmitted & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = creditApplicationSubmitted;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leospaybyplow/credit_application_submitted/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CreditApplicationSubmitted entity.
 */
export function createCreditApplicationSubmitted(creditApplicationSubmitted: CreditApplicationSubmitted){
    return {
        schema: 'iglu:com.leospaybyplow/credit_application_submitted/jsonschema/1-0-0',
        data: creditApplicationSubmitted
    }
}

/**
 * Tracks a FinancingCalculatorUsed event specification.
 * ID: 015dc7d6-cba5-440f-8387-5e021e8e3624
 */
export function trackFinancingCalculatorUsedSpec(financingCalculatorUsed: FinancingCalculatorUsed & ContextsOrTimestamp<UserCreditProfile | DeviceContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '015dc7d6-cba5-440f-8387-5e021e8e3624',
        name: 'financing_calculator_used',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(financingCalculatorUsed.context)
        ? [...financingCalculatorUsed.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedFinancingCalculatorUsed = {
        ...financingCalculatorUsed,
        context,
    };

    trackFinancingCalculatorUsed<UserCreditProfile | DeviceContext | EventSpecification>(modifiedFinancingCalculatorUsed, trackers);
}
/**
 * Tracks a PaymentCompleted event specification.
 * ID: 5bfe5401-1f8c-48e3-8eee-3921f2a32ec2
 */
export function trackPaymentCompletedSpec(paymentCompleted: PaymentCompleted & ContextsOrTimestamp<UserCreditProfile | LoanContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '5bfe5401-1f8c-48e3-8eee-3921f2a32ec2',
        name: 'payment_completed',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(paymentCompleted.context)
        ? [...paymentCompleted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPaymentCompleted = {
        ...paymentCompleted,
        context,
    };

    trackPaymentCompleted<UserCreditProfile | LoanContext | EventSpecification>(modifiedPaymentCompleted, trackers);
}
/**
 * Tracks a CreditApplicationStepCompleted event specification.
 * ID: 5db3c34e-8d90-4732-837b-e9f333497c97
 */
export function trackCreditApplicationStepCompletedSpec(creditApplicationStepCompleted: CreditApplicationStepCompleted & ContextsOrTimestamp<UserCreditProfile | DeviceContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '5db3c34e-8d90-4732-837b-e9f333497c97',
        name: 'credit_application_step_completed',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(creditApplicationStepCompleted.context)
        ? [...creditApplicationStepCompleted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCreditApplicationStepCompleted = {
        ...creditApplicationStepCompleted,
        context,
    };

    trackCreditApplicationStepCompleted<UserCreditProfile | DeviceContext | EventSpecification>(modifiedCreditApplicationStepCompleted, trackers);
}
/**
 * Tracks a PaymentInitiated event specification.
 * ID: 6055b5de-5c85-4c79-82af-87056579bcf0
 */
export function trackPaymentInitiatedSpec(paymentInitiated: PaymentInitiated & ContextsOrTimestamp<UserCreditProfile | LoanContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '6055b5de-5c85-4c79-82af-87056579bcf0',
        name: 'payment_initiated',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(paymentInitiated.context)
        ? [...paymentInitiated.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPaymentInitiated = {
        ...paymentInitiated,
        context,
    };

    trackPaymentInitiated<UserCreditProfile | LoanContext | EventSpecification>(modifiedPaymentInitiated, trackers);
}
/**
 * Tracks a CustomerIdentification event specification.
 * ID: 915f78c6-8054-463f-a728-9f80817f4893
 */
export function trackCustomerIdentificationSpec(customerIdentification: CustomerIdentification & ContextsOrTimestamp<UserCreditProfile>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '915f78c6-8054-463f-a728-9f80817f4893',
        name: 'customer_identification',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(customerIdentification.context)
        ? [...customerIdentification.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCustomerIdentification = {
        ...customerIdentification,
        context,
    };

    trackCustomerIdentification<UserCreditProfile | EventSpecification>(modifiedCustomerIdentification, trackers);
}
/**
 * Tracks a DeviceViewed event specification.
 * ID: a56b84a7-3e20-4622-82af-0cbc06179469
 */
export function trackDeviceViewedSpec(deviceViewed: DeviceViewed & ContextsOrTimestamp<UserCreditProfile | DeviceContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'a56b84a7-3e20-4622-82af-0cbc06179469',
        name: 'device_viewed',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(deviceViewed.context)
        ? [...deviceViewed.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedDeviceViewed = {
        ...deviceViewed,
        context,
    };

    trackDeviceViewed<UserCreditProfile | DeviceContext | EventSpecification>(modifiedDeviceViewed, trackers);
}
/**
 * Tracks a CreditDecisionViewed event specification.
 * ID: c108b1f5-cce4-410e-b0f2-81ab22428f5b
 */
export function trackCreditDecisionViewedSpec(creditDecisionViewed: CreditDecisionViewed & ContextsOrTimestamp<UserCreditProfile | DeviceContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'c108b1f5-cce4-410e-b0f2-81ab22428f5b',
        name: 'credit_decision_viewed',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(creditDecisionViewed.context)
        ? [...creditDecisionViewed.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCreditDecisionViewed = {
        ...creditDecisionViewed,
        context,
    };

    trackCreditDecisionViewed<UserCreditProfile | DeviceContext | EventSpecification>(modifiedCreditDecisionViewed, trackers);
}
/**
 * Tracks a DeviceLockSimulated event specification.
 * ID: c5fc596a-ef49-43f0-8370-cdc099a413d1
 */
export function trackDeviceLockSimulatedSpec(deviceLockSimulated: DeviceLockSimulated & ContextsOrTimestamp<UserCreditProfile | LoanContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'c5fc596a-ef49-43f0-8370-cdc099a413d1',
        name: 'device_lock_simulated',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(deviceLockSimulated.context)
        ? [...deviceLockSimulated.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedDeviceLockSimulated = {
        ...deviceLockSimulated,
        context,
    };

    trackDeviceLockSimulated<UserCreditProfile | LoanContext | EventSpecification>(modifiedDeviceLockSimulated, trackers);
}
/**
 * Tracks a CreditApplicationStarted event specification.
 * ID: d105dd67-7df8-47fe-834b-6f998c23924a
 */
export function trackCreditApplicationStartedSpec(creditApplicationStarted: CreditApplicationStarted & ContextsOrTimestamp<UserCreditProfile | DeviceContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'd105dd67-7df8-47fe-834b-6f998c23924a',
        name: 'credit_application_started',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(creditApplicationStarted.context)
        ? [...creditApplicationStarted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCreditApplicationStarted = {
        ...creditApplicationStarted,
        context,
    };

    trackCreditApplicationStarted<UserCreditProfile | DeviceContext | EventSpecification>(modifiedCreditApplicationStarted, trackers);
}
/**
 * Tracks a CreditApplicationSubmitted event specification.
 * ID: fbeb2eb4-013a-4457-8c25-221d211fc9e8
 */
export function trackCreditApplicationSubmittedSpec(creditApplicationSubmitted: CreditApplicationSubmitted & ContextsOrTimestamp<UserCreditProfile | DeviceContext>, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: 'fbeb2eb4-013a-4457-8c25-221d211fc9e8',
        name: 'credit_application_submitted',
        data_product_id: '97bcedb4-b7da-401c-8b6d-1fa89829c8ad',
        data_product_name: 'Leo&#x27;s Pay by Plow',
        data_product_domain: ''
    });

    const context = Array.isArray(creditApplicationSubmitted.context)
        ? [...creditApplicationSubmitted.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCreditApplicationSubmitted = {
        ...creditApplicationSubmitted,
        context,
    };

    trackCreditApplicationSubmitted<UserCreditProfile | DeviceContext | EventSpecification>(modifiedCreditApplicationSubmitted, trackers);
}


