apiVersion: v1
resourceType: data-structure
meta:
  hidden: false
  schemaType: event
  customData: {}
data:
  $schema: http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#
  self:
    vendor: com.leospaybyplow
    name: credit_application_submitted
    format: jsonschema
    version: 1-0-0
  type: object
  properties:
    device_id:
      type: string
    requested_amount:
      type: number
    income_bracket:
      type: string
      enum:
        - under_500
        - 500_1000
        - 1000_2000
        - over_2000
  required:
    - device_id
    - requested_amount
    - income_bracket
  additionalProperties: false
